name:                space-hs
version:             0.1.0.0
github:              "Techgineers7725/space.hs"
license:             BSD-3-Clause
author:              "Execute, Hexatorum"
maintainer:          "execute@erisws.com"
copyright:           "2025 Execute, Hexatorum"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Techgineers7725/space.hs#readme>

dependencies:
- base >= 4.7 && < 5

## containers
- array
- containers
- unordered-containers
- vector

## text
- bytestring
- text

## networking
- tls
- x509
- quic
- quic-simple
- network
- serialise
- crypton

## extra I/O
- extra
- random
- StateVar
- exceptions
- unliftio

## memory
- memory
- primitive

## graphics
- dear-imgui
- sdl2
- OpenAL
- JuicyPixels
- atlas

## concurrency
- async
- stm

## other stuff
- lens
- apecs # ECS
- aeson # JSON
- OpenGL # sound
- linear # linear algebra
- hourglass # time

ghc-options: []

default-extensions:
## types
- TypeFamilies
- TypeFamilyDependencies

- TypeOperators

- DataKinds
- KindSignatures
- PolyKinds
- ConstraintKinds

# records
- DisambiguateRecordFields
- DuplicateRecordFields
- OverloadedRecordDot
- RecordWildCards
- NamedFieldPuns

# deriving
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DeriveDataTypeable
- DeriveAnyClass
- StandaloneDeriving
- GeneralizedNewtypeDeriving

- GADTs
- GADTSyntax
- ExistentialQuantification
- ViewPatterns

- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- DefaultSignatures

- MultiParamTypeClasses
- ScopedTypeVariables
- RankNTypes

- NoStarIsType # this should just be in base haskell lol
- ExplicitForAll

- TypeApplications
- PatternSynonyms

- FunctionalDependencies

## syntax
- BangPatterns
- QuasiQuotes
- TupleSections
- TemplateHaskell

- EmptyCase
- LambdaCase
- BlockArguments
- MultiWayIf
- ImportQualifiedPost

- OverloadedStrings
#- OverloadedLists # apparently this breaks SDL init

library:
  source-dirs:
  - assets
  - src/common

executables:
  client:
    main: Main.hs
    source-dirs:
    - app/client
    - src/client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-hs

  server:
    main: Main.hs
    source-dirs:
    - app/server
    - src/server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - space-hs
